#!/bin/bash

# generateId
#
# by alic3dev (2024)
#
# A function to generate a random alphanumeric ID

# generateId()
# @parameter (optional) idLength - The length of the ID (Default: 32)
# @returns A random alphanumeric ID that is `idLength` long
generateId() {
  __idLength=$1

  if [[ -z $__idLength ]]; then
    __idLength=32
  fi

  __id=$(
    head -c $(($__idLength * 100)) /dev/urandom |
    tr -dc "[:alnum:]" |
    head -c $__idLength
  )

  if [[ ${#__id} -lt $__idLength ]]; then
    # This shouldn't ever really happen
    # There is a potential for an infinite loop in extreme cases
    # Protecting against that edge case is too heavy to consider

    generateId $__idLength
  else
    echo -n $__id
  fi
}
