#!/bin/bash

# log2n
#
# by alic3dev (2024)
#
# Logarithmic 2 implementation

log2n() {
  local result=0

  for ((y=$(($1 - 1)); y > 0; y >>= 1)); do
    result=$(($result + 1))
  done

  printf $result
}
