#!/bin/bash

# sh/functions/padRight
#
# by alic3dev (2024)
#
# A collection of string padding functions

# padRight()
# @parameter string - The string to pad
# @parameter length - The length to pad to
# @parameter *padding - The string to pad with
padRight() {
  local result="$1"
  local length=$2

  if [[ -z $length ]]; then
    length=${#result}
  fi

  if [[ ${#result} -ge $length ]]; then
    printf "$result"
    exit 0
  fi

  local padding=$3

  if [[ -z $padding ]]; then
    padding=" "
  fi

  while [[ ${#result} -lt $length ]]; do
    result="$result$padding"
  done

  printf "${result:$((${#result} - $length))}"
}
